name: Pipeline de CI

on:
  push:
    branches: [ "main" ]

jobs:
  testes:
    name: Testes unitários
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Configurar a linguagem - nosso caso Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar as dependências
        run: |
          pip install -r requirements.txt

      - name: Rodar os testes unitários
        run: |
          pytest tests/unit